config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: 'lists#index'
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy

  patch '/validate/:id', to: 'bookmarks#validate', as: :validate
  patch '/unwatched/:id', to: 'bookmarks#unwatched', as: :unwatched
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: { scope: :list_id, message: "is already in the list" }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  acts_as_taggable_on :tags
  has_many :bookmarks, dependent: :delete_all
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save!
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  def validate
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.update(status: true)
    redirect_to list_path(@list)
  end

  def unwatched
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.update(status: false)
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :status)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new # <-- You need this now.
    @bookmarks = @list.bookmarks
    @watched_bookmarks = @bookmarks.where(status: true)
    @unwatched_bookmarks = @bookmarks.where(status: false)
  end

  def new
     @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :tag_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_new_bookmark.html.erb
<div class="open">
  +
</div>

<div class="frame d-none">
<%# display none pour cacher %>
  <div class="frame-content">

<div class='close'>
  <i class="fas fa-times"></i>
</div>

<h3 id="popup-title">Add a movie to your <%= @list.name %> list</h3>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <br>
  <%= f.submit "ADD IT", class: "btn-big" %>
<% end %>

  </div>
</div>
<%#= link_to "Back", list_path(@list) %>

app/views/bookmarks/new.html.erb
<h3 id="popup-title">Add a movie to your <%= @list.name %> list</h3>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <br>
  <%= f.submit "ADD IT", class: "btn-big" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
      <%= render 'shared/navbar' %>
      <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="header">
  <%#= image_tag "https://images.unsplash.com/photo-1596146828740-8a0117f437e5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80" %>
</div>

<div class="container index">
  <ul class="menu">
    <li> <%= link_to "NEW LIST", new_list_path, class: "link-menu" %> </li>
    <li> <%= link_to "ALL MOVIES", root_path, class: "link-menu" %> </li>
    <li> <%= link_to "MY FRIENDS", root_path, class: "link-menu" %> </li>
  </ul>
  <div class="lists">
    <h1>My Lists</h1>
    <div class="lists-card">
      <% @lists.each_with_index do |list, index| %>
        <div class="card-odd">
          <%= index %>
          <%= link_to list.name, list_path(list) %>
        </div>
        <br>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container new">

  <h1>CREATE A NEW LIST</h1>

  <i class="fas fa-chevron-left"></i>
  <%= link_to "BACK", lists_path, class: "back" %>

  <div class="form">
    <%= simple_form_for(@list) do |f| %>
      <%= f.input :name, placeholder: 'NAME'%>
      <%= f.input :tag_list, placeholder: "TAGS" %>
      <%= f.input :tag_list, placeholder: 'IMAGES' %>
      <%= f.button :submit, "CREATE" %>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container show">

  <div class="head d-flex justify-content-between align-items-baseline">
    <h1><%= @list.name %></h1>
    <%#= link_to "+", new_list_bookmark_path(@list)  %>
    <%= render 'bookmarks/new_bookmark' %>
  </div>
  <div class="nav nav-tabs btn-mybookmark">
    <a class="nav-item nav-link active" href="#first_tab" data-toggle="tab">🎬 TO WATCH</a>
    <a class="nav-item nav-link" href="#second_tab" data-toggle="tab">✓ WATCHED</a>
  </div>
   <div class="tab-content">
      <div class="tab-pane active" id="first_tab">
        <% @unwatched_bookmarks.each do |bookmark| %>
          <div class="bookmark-card">
            <%= image_tag bookmark.movie.poster_url %>

            <div class="info">
              <h3><%= bookmark.movie.title%></h3>
              <p><%= bookmark.comment %></p>
              <p><%= bookmark.status %></p>
            </div>
            <div class="logos">
               <%= link_to validate_path(bookmark), method: :patch do %>
               <i class="far fa-square"> </i>
               <% end %>
               <%= link_to validate_path(bookmark), method: :patch do %>
              <i class="far fa-star "></i>
              <% end %>
            </div>

          </div>
        <% end %>
      </div>
      <div class="tab-pane" id="second_tab">
        <% @watched_bookmarks.each do |bookmark| %>
          <div class="bookmark-card">
            <%= image_tag bookmark.movie.poster_url %>

            <div class="info">
              <h3><%= bookmark.movie.title%></h3>
              <p><%= bookmark.comment %></p>
              <p><%= bookmark.status %></p>
            </div>
            <div class="logos">
               <%= link_to unwatched_path(bookmark), method: :patch do %>
               <i class="far fa-check-square"></i>
               <% end %>
               <%= link_to validate_path(bookmark), method: :patch do %>
              <i class="far fa-star "></i>
              <% end %>
            </div>

          </div>
        <% end %>
      </div>
    </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= 'transparent' if action_name == 'index' %>">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "cinema.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
<!--       <li class="nav-item active">
        <%#= link_to "My List", "#", class: "link-navbar" %>
      </li>
      <li class="nav-item">
        <%#= link_to "New List", "#", class: "link-navbar" %>
      </li> -->
      <li class="nav-item dropdown">
        <%= image_tag "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=934&q=80", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>